"""new field in user model

Revision ID: 222adb49f669
Revises: 0411f3b34b26
Create Date: 2020-12-14 17:11:23.317003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222adb49f669'
down_revision = '0411f3b34b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('abot_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'abot_me')
    # ### end Alembic commands ###
